// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbxYTcE4NsqOm1dNtcYKXkPiWkPKe81RM',
    appId: '1:335615945762:web:618d92d4471f0d162a6e7b',
    messagingSenderId: '335615945762',
    projectId: 'chat-app-dbba3',
    authDomain: 'chat-app-dbba3.firebaseapp.com',
    storageBucket: 'chat-app-dbba3.firebasestorage.app',
    measurementId: 'G-63NX0XF0P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUR3mLqIGlIVal77QJ3diBKh9HRIppbjo',
    appId: '1:335615945762:android:3910eb0e42ad06702a6e7b',
    messagingSenderId: '335615945762',
    projectId: 'chat-app-dbba3',
    storageBucket: 'chat-app-dbba3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhnzIvTxeL0ag0KhZF1HqX2HkX4AEgndw',
    appId: '1:335615945762:ios:12679755757064792a6e7b',
    messagingSenderId: '335615945762',
    projectId: 'chat-app-dbba3',
    storageBucket: 'chat-app-dbba3.firebasestorage.app',
    iosBundleId: 'com.example.stageWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhnzIvTxeL0ag0KhZF1HqX2HkX4AEgndw',
    appId: '1:335615945762:ios:12679755757064792a6e7b',
    messagingSenderId: '335615945762',
    projectId: 'chat-app-dbba3',
    storageBucket: 'chat-app-dbba3.firebasestorage.app',
    iosBundleId: 'com.example.stageWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwjzPPYxiI15xcSZhoZuDvu9XFfJ-j7C0',
    appId: '1:335615945762:web:7100a158582e56862a6e7b',
    messagingSenderId: '335615945762',
    projectId: 'chat-app-dbba3',
    authDomain: 'chat-app-dbba3.firebaseapp.com',
    storageBucket: 'chat-app-dbba3.firebasestorage.app',
    measurementId: 'G-M9VCTB9YXP',
  );
}
